version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_sd
    ports:
      - "5436:5432"
    expose:
      - "5436"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sd