version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_sd
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sd
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql